### ISSUE TITLE
So how many GPUs do you use for inference 33B model?

### ISSUE THREAD

**Issue by YixinSong-e** [SafeAILab/EAGLE#1]
Amazing Work! I want to know that how many GPUs do you use for inference 33B model?

**Comment by Liyuhui-12** [comment]
Thank you for your interest. The GPU requirements for the 33B model depend on the precision used. With FP16 precision, the weights of the 33B model require 66GB of VRAM, and additional storage is needed for attention and other components. For vanilla autoregressive generation of long sequences, 4xRTX 3090 GPUs are needed, and EAGLE also uses 4xRTX 3090 GPUs for inference.
