### ISSUE TITLE
combinable with vllm

### ISSUE THREAD

**Issue by jiangix-paper** [SafeAILab/EAGLE#10]
Great work. How can I combine the eagle with vllm？

**Comment by Liyuhui-12** [comment]
Thank you for your interest. We will support vLLM in our subsequent updates.

**Comment by tjtanaa** [comment]
@Liyuhui-12 Great Job~! looking forward to it. May I know what's the timeline to expect EAGLE to be integrated into vLLM?

**Comment by Liyuhui-12** [comment]
Thank you for your interest. We are in the process of writing the paper on EAGLE, and after completing the paper, we will integrate vLLM and others.
