### ISSUE TITLE
How to use the eagle model trained by myself

### ISSUE THREAD

**Issue by yanjunplay** [SafeAILab/EAGLE#100]
Hello!

Related to my previous question, I trained a new eagle model with my fine tuned llama3 70b base model. After some iterations, I got state with files:

`optimizer.bin  pytorch_model_1.bin  pytorch_model.bin  random_states_0.pkl  scheduler.bin`

I believe these are training checkpoints and are different from the loadable models like https://huggingface.co/yuhuili/EAGLE-LLaMA3-Instruct-70B

How to convert training checkpoints to loadable eagle models? 

I was trying to load pytorch_model.bin with EaModel.from_pretrained but got error
```
RuntimeError: Error(s) in loading state_dict for Model:
        Unexpected key(s) in state_dict: "fc.bias".
```

I used `accelerate launch -m --mixed_precision=bf16 eagle.train.main --tmpdir [path of data]\
--cpdir [path of checkpoints] -- configpath [path of config file]` to train.

**Comment by yanjunplay** [comment]
I assume there will be some function like save_pretrained for EaModel

**Comment by Liyuhui-12** [comment]
Your config.json contains "bias": false, which affects the model structure initialization during the inference phase but not during the training phase. You just need to remove "bias": false, and there is no need to retrain the model.

**Comment by xiaonengmiao** [comment]
Hi, I have a question here too. I also got these state files:

`optimizer.bin  pytorch_model_1.bin  pytorch_model.bin  random_states_0.pkl  scheduler.bin`

I believe `pytorch_model.bin` is the eagle model from the code. But what is `pytorch_model_1.bin`? It is not used anywhere in the code.
