### ISSUE TITLE
What's the ideal loss and accuracy for eagle training

### ISSUE THREAD

**Issue by yanjunplay** [SafeAILab/EAGLE#101]
As we discussed, I am training eagle weights with my fine tuned llama 3 70B.

Test Epoch [17/20], Loss: 0.5081
Test Accuracy: 82.20%

Currently, it's at loss 0.5081 and accuracy 82.2%.

From your experience, what's the ideal loss and accuracy after the training? Thanks!!

**Comment by yanjunplay** [comment]
I was training with batch size = 2 on 1 H100 hosts (8 cards)

**Comment by hongyanz** [comment]
Top-1 Test Accuracy 82.2% looks normal.

**Comment by yanjunplay** [comment]
Yep. Thanks. I finished training with:

Test Epoch [21/20], Loss: 0.5011
Test Accuracy: 82.80%

I am doing more perf testing today. Will report back. Thanks again!
