### ISSUE TITLE
Is this expected behavior?

### ISSUE THREAD

**Issue by qwedaq** [SafeAILab/EAGLE#113]
Hi, 

I am running EAGLE2 code for LLaMA 3 8B model ('meta-llama/Meta-Llama-3-8B-Instruct'). Before the warmup I get the following message that certain weights are newly initialised and needs to be trained. I am running the following command

 CUDA_VISIBLE_DEVICES=0 python3 -m eagle.evaluation.gen_ea_answer_llama3chat --ea-model-path 'yuhuili/EAGLE-LLaMA3-Instruct-8B' --base-model-path 'meta-llama/Meta-Llama-3-8B-Instruct'
 
Am I executing it correctly or do I need to do any further training? 

I am attaching below the message 
<img width="1134" alt="e1" src="https://github.com/user-attachments/assets/eab2ae26-a8e2-4143-b5d9-12d71426b65a">

Thanks in advance

**Comment by Liyuhui-12** [comment]
This is normal.

**Comment by qwedaq** [comment]
Okay, thank you for your response
