### ISSUE TITLE
Support Qwen2 in Eagle's inference framwork

### ISSUE THREAD

**Issue by xiaoyong-z** [SafeAILab/EAGLE#114]
Qwen2 eagle model now has been uploaded to hf repo. I can't wait to test its performance. 
However, it seems that eagle's inference framework doesn't support qwen2, when will it officially be supported?

**Comment by xiaoyong-z** [comment]
I also want to know what's the speedup of QWEN2 compared with other speculative decoding models

**Comment by hongyanz** [comment]
The code has been updated to support qwen2.

**Comment by kechunFIVE** [comment]
> Qwen2 eagle model now has been uploaded to hf repo. I can't wait to test its performance. However, it seems that eagle's inference framework doesn't support qwen2, when will it officially be supported?

Can you run the 'qwen2' inference? I seem to have a problem here, the model cannot be loaded.
