### ISSUE TITLE
Confusion in Figure 5 (b) of EAGLE2 paper

### ISSUE THREAD

**Issue by SimonSongg** [SafeAILab/EAGLE#115]
Hi,

Thanks for your great series of work. I am reading your EAGLE 2 paper and have some confusions.

For figure 5 (b), you said "each point representing a query", in my understanding, "a query" means building the draft tree once, in other words, going through the drafting stage once. Then in verification stage, the target LLM will check if the token in every position is accepted or not. So how could 1 position (let's say position 1), get an acceptance rate within one query. It seems can only be accepted or not accepted. If it is an average acceptance rate for this position for a number of drafting stages, it will make more sense to me.

Could you please explain a little bit about this? Thanks for your time~

Best

**Comment by hongyanz** [comment]
The accept rate is defined as min(1, p/q), which can be between 0 and 1.

**Comment by SimonSongg** [comment]
> The accept rate is defined as min(1, p/q), which can be between 0 and 1.

**Comment by SimonSongg** [comment]
> The accept rate is defined as min(1, p/q), which can be between 0 and 1.


Thanks for your reply. Could you please further explain what p and q mean here? 

Thank you.
