### ISSUE TITLE
Evaluating Eagle on HumanEval, GSM8K, Alpaca, CNN/DM, and Natural Questions Datasets

### ISSUE THREAD

**Issue by garipovroma** [SafeAILab/EAGLE#124]
Hello!

Thank you for your work!

I’ve been reviewing your code and noticed that the published evaluation currently supports only the MTBench dataset. However, in the paper, you reported speedup and $\tau$ for the HumanEval, GSM8K, Alpaca, CNN/DM, and Natural Questions datasets as well(Table 1 in the EAGLE-2 paper). Could you please provide scripts for evaluating Eagle with these datasets?

**Comment by Liyuhui-12** [comment]
You can use `--bench-name` to specify the dataset, such as `humaneval`.

**Comment by Raghav-2002** [comment]
Hi,
Thanks for your work !
Could you please let us know why have you used only 80 samples from all datasets in the eval set. Are the shared .jsonl just randomly sampled set of 80 questions from eval set or is it that the numbers reported in the paper are also on these 80 samples.

**Comment by Liyuhui-12** [comment]
Testing with the full dataset is too expensive, so selecting 80 data points is a common practice, as seen in Medusa, Spec-bench, etc.

**Comment by garipovroma** [comment]
Thank you so much!
