### ISSUE TITLE
Regarding training data of EAGLE

### ISSUE THREAD

**Issue by KanghoonYoon** [SafeAILab/EAGLE#128]
I want to clarify the portion of training dataset, ShareGPT.

The current code uses the 100 samples as training dataset for EAGLE.

But in the paper, EAGLES is trained with 68,000 samples.

What should I follow to reproduce EAGLES from scratch ? :)

**Comment by Liyuhui-12** [comment]
The default value of 100 is for debugging purposes; you can specify this parameter during training.
