### ISSUE TITLE
Could not reproduce Acceptance Length for Llama 2 7B Chat Model with chain drafts

### ISSUE THREAD

**Issue by luyuzhe111** [SafeAILab/EAGLE#132]
Hello EAGLE authors,

Thanks for your great work! I am currently trying to reproduce EAGLEv1 results for Llama 2 7B Chat model, specifically in terms of acceptance length between chain and tree drafts. From the paper, I noticed that the $\tau$ is 3.0 for chain draft and 3.62 for tree draft. For chain drafts, I added this config to `eagle/model/choices.py` file: `chain = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0, 0]]`
<img width="433" alt="Screenshot 2024-09-18 at 3 08 58 PM" src="https://github.com/user-attachments/assets/14eae805-0cc4-49b6-bfeb-698b38542b92">

However, when I try to reproduce using the v1 codebase and the provided checkpoint with temp=0 and dataset=mt_bench, I only got $\tau$ = 2.3 for chain draft instead of 3, which is a significant drop, though I did manage to reproduce $\tau$ = 3.68 for tree drafts. I wonder if you can obtain this reported result for chain draft using the v1 codebase, or there was any update to the codebase that was not committed. Thanks for your time and looking forward to your reply!

**Comment by Liyuhui-12** [comment]
The average acceptance length includes the one token generated by the target model. Does your result include this? Other possible reasons may also include incorrect draft model weights or templates.

**Comment by luyuzhe111** [comment]
Hi Yuhui,

Thanks for your reply! It was actually due to a bug. For anyone else having trouble with this, note that we need to update the tree shape for both the base model and the eagle heads (as in cnet). When you want to use something other than the default tree, please remember to update it for both base and eagle model. Currently, the eagle model by default initializes to the default tree as in `choices.py`.

**Comment by adamxyang** [comment]
Thanks for sharing! I've been following along and noticed that for chain drafts, we need to add `chain = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0, 0]]` to the `eagle/model/choices.py` file. Could you clarify if there are additional changes required in `cnets.py` or other parts of the codebase to properly configure chain drafts? Thanks!

**Comment by luyuzhe111** [comment]
please make sure you initialize the tree with chain here https://github.com/SafeAILab/EAGLE/blob/v1/eagle/model/cnets.py#L498

**Comment by adamxyang** [comment]
Thanks! Just noticed we need to switch to the v1 branch to use chain draft.
