### ISSUE TITLE
How could I train llama3-8B?

### ISSUE THREAD

**Issue by 870572761** [SafeAILab/EAGLE#139]
![image](https://github.com/user-attachments/assets/b9d669ac-2eec-4491-a155-d1d03dcc204f)
My args includes "--basepath","/data/lei/localmodel/meta-llama/Meta-Llama-3-8B-Instruct". But I have found there is not the keyword "lm_head.weight" in the configs file of llama3-8B!!!
![image](https://github.com/user-attachments/assets/60659b03-6d12-4703-8db8-dd301328923b)
![image](https://github.com/user-attachments/assets/62d7aac2-5b23-481d-8499-0a925aee3268)
The final layer is this. Could you tell me how to change it ?

**Comment by 870572761** [comment]
it is the same if my args includes "--basepath","/data/lei/localmodel/lmsys/vicuna-7b-v1.3", I change my model
![image](https://github.com/user-attachments/assets/7944c2e7-8f33-4e21-b21b-7528f87c68a8)

**Comment by ljc0359** [comment]
Hi Haodong,

Good to see you here again; looks like you are very familiar with this codebase. Might I ask have you solved this problem already?

I try to run MT-bench using LLaMA3-Instruct 8B (using the one provided here https://huggingface.co/yuhuili/EAGLE-LLaMA3-Instruct-8B), but some weights seem to be missing 

`Some weights of the model checkpoint at checkpoint/checkpoints were not used when initializing LlamaForCausalLM: ['fc.weight']
- This IS expected if you are initializing LlamaForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing LlamaForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at checkpoint/checkpoints and are newly initialized: ['layers.0.self_attn.rotary_emb.inv_freq', 'norm.weight', 'lm_head.weight', 'layers.0.input_layernorm.weight']
`
And it seems like there is no tokenizer from the link they provided, may I ask how should I handle missing weights and missing tokenizer in this case?

Thank you so much for your time and any assistant!
