### ISSUE TITLE
Issue about the comparison with Lookahead

### ISSUE THREAD

**Issue by lethean1** [SafeAILab/EAGLE#145]
Hi, thanks for you great work! The issue I am concerned about is the deployed parallelism when compared to Lookahead. As far as I know, Lookahead currently does not supports tensor parallelism which is important in LLM serving. Do you achieve this on Lookahead, or are you just comparing it with pipeline parallelism version?

**Comment by Liyuhui-12** [comment]
Thank you for your interest. EAGLE currently does not support tensor parallelism.
