### ISSUE TITLE
Question regarding sampling technique in EAGLE papers

### ISSUE THREAD

**Issue by llsj14** [SafeAILab/EAGLE#148]
Hello,

Thank you for your excellent work on EAGLE and EAGLE-2. I have been reading both papers, as well as Medusa.

The accept rate and speed-up metrics from the various experiments in the paper are valuable.
However, I have a question regarding the sampling method you used. I’m curious whether you applied rejection sampling or the typical acceptance scheme proposed by Medusa.

The papers typically show a 10-15% difference in accept rate, aside from the sampling method. It would be helpful to understand which method you used in your experiments.

Thank you

**Comment by Liyuhui-12** [comment]
Thank you for your interest. We employ strict speculative sampling to ensure lossless results, rather than using the typical acceptance scheme found in Medusa.

**Comment by llsj14** [comment]
Ah, so it is rejection sampling. Thank you for your answer.
