### ISSUE TITLE
Support Chinese-LLaMA-Alpaca-2?

### ISSUE THREAD

**Issue by skykiseki** [SafeAILab/EAGLE#15]
Nice work!
I just wonder will EAGLE support Chinese-LLaMA-Alpaca-2 and will you show the paper in the future? ?

model url: https://github.com/ymcui/Chinese-LLaMA-Alpaca-2

Hope for your response, thx

**Comment by skykiseki** [comment]
And I want to know the difference between EAGLE and SpecInfer. I'm guessing that the tree verification part of the two is the same, right?

**Comment by Liyuhui-12** [comment]
We will support more models in the future.

Yes, the tree verification part is the same. Our main contribution lies in the guessing and drafting part, which is different from SpecInfer. Also, the application scope of EAGLE is different from SpecInfer. EAGLE is not limited to distributed LLM inference or offloading-based LLM inference, and it can be used in more general situations.

**Comment by skykiseki** [comment]
> We will support more models in the future.
> 
> Yes, the tree verification part is the same. Our main contribution lies in the guessing and drafting part, which is different from SpecInfer. Also, the application scope of EAGLE is different from SpecInfer. EAGLE is not limited to distributed LLM inference or offloading-based LLM inference, and it can be used in more general situations.

OK,Looking forward to the upcoming updates, thank you.
