### ISSUE TITLE
There is a problem with reproduction

### ISSUE THREAD

**Issue by skylee-01** [SafeAILab/EAGLE#154]
![image](https://github.com/user-attachments/assets/65f7125b-bb73-4813-abc3-759db7bdeda7)
![image](https://github.com/user-attachments/assets/9ba5e555-001f-484d-9ddd-e5d746634e1d)

**Comment by skylee-01** [comment]
Please help me see what the problem is.

**Comment by skylee-01** [comment]
CUDA_VISIBLE_DEVICES="3, 4,5" accelerate launch  --config_file config.yaml  eagle/train/main.py --tmpdir /home/lisiqi23/work/eagle_train/EAGLE1/EAGLE/eagle/ge_data/out_0 --cpdir /home/lisiqi23/work/eagle_train/EAGLE1/EAGLE/eagle/model_out --configpath /home/lisiqi23/work/eagle_train/Qwen2-7B-Instruct

**Comment by skylee-01** [comment]
![image](https://github.com/user-attachments/assets/a50febf0-3585-43c8-97cb-b5eb351d1adc)

**Comment by skylee-01** [comment]
模型推理的时候，卡住了。。。不知道是不是配置的不正确。。。

**Comment by Liyuhui-12** [comment]
It appears to be an out-of-memory issue.

**Comment by skylee-01** [comment]
It has been solved, thank you.
