### ISSUE TITLE
Support Chinese Task

### ISSUE THREAD

**Issue by Ishiki-Iroha** [SafeAILab/EAGLE#16]
We tested a small number of Chinese tasks(about 50 tasks) on Vicuna (7b, 13b) and found that the acceleration ratio of Chinese tasks was lower than that of English tasks. Is this in line with expectations? Here are some results:

|| vicuna-7b |vicuna-13b|
|-|-|-|
|Baseline(tokens/s) |39.63| 23.13|
|Eagle(tokens/s) |65.59 |42.27
|Ratio |1.66| 1.83|

**Comment by hongyanz** [comment]
We use ShareGPT dataset to train EAGLE. Here is the description of the [ShareGPT dataset](https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered): Removing excessive unicode (indicative of Chinese or Korean text, usually). Therefore, acceleration on Chinese task is totally out-of-distribution.

If you are interested in Chinese task, we would suggest using Chinese corpus to train EAGLE.
