### ISSUE TITLE
OSError when download weights from huggingface

### ISSUE THREAD

**Issue by ZepinLi** [SafeAILab/EAGLE#18]
OSError: Can't load tokenizer for 'yuhuili/EAGLE-llama2-chat-7B'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'yuhuili/EAGLE-llama2-chat-7B' is the correct path to a directory containing all relevant files for a LlamaTokenizerFast tokenizer.

**Comment by ZepinLi** [comment]
Note: i followed the pipeline of transformers to download EAGLE team's open source trained weights, but failed due to OSError of tokenizer. do you know why? much appreciation.

**Comment by Liyuhui-12** [comment]
Did you use transformers.pipeline? Currently, EAGLE cannot be used in that way. You can follow the instructions in the Readme to use EAGLE.

**Comment by ZepinLi** [comment]
I try download from huggingface page manually, and it worked. I'll try with writing code later. thx!
