### ISSUE TITLE
Difference between Eagle and SpecInfer

### ISSUE THREAD

**Issue by Hsword** [SafeAILab/EAGLE#2]
Hi, Eagle team, I am one of the authors of SpecInfer (https://arxiv.org/pdf/2305.09781.pdf). I just noticed your work on exploring speculative inference of LLMs. I am curious about some contents in your blog (https://sites.google.com/view/eagle-llm, such as token tree structure and multi-round speculative sampling), what's the difference compared with the token tree design and multi-step speculative sampling in our SpecInfer paper? As you mentioned Medusa, they referred our work to respect our contributions about tree attention (https://sites.google.com/view/medusa-llm).

**Comment by Liyuhui-12** [comment]
Thank you for the reminder. The validation part of EAGLE is the same as SpecInfer. Their difference lies in the guessing part.

**Comment by haiduo** [comment]
> Hi, Eagle team, I am one of the authors of SpecInfer (https://arxiv.org/pdf/2305.09781.pdf). I just noticed your work on exploring speculative inference of LLMs. I am curious about some contents in your blog (https://sites.google.com/view/eagle-llm, such as token tree structure and multi-round speculative sampling), what's the difference compared with the token tree design and multi-step speculative sampling in our SpecInfer paper? As you mentioned Medusa, they referred our work to respect our contributions about tree attention (https://sites.google.com/view/medusa-llm).

Thanks for your work, but I'm curious if there are other implementations of SpecInfer that strip out the FlexFlow system, such as a pure Python version?
