### ISSUE TITLE
No pytorch.bin is generated after training is done

### ISSUE THREAD

**Issue by tjtanaa** [SafeAILab/EAGLE#21]
I have rerun the whole training pipeline for the vicuna 7b model.
The training ended successfully. However, there is no `pytorch.bin` is generated. May I know why?

The following folders and files are what I get.
Folders:
```
state_0  state_10  state_12  state_15  state_17  state_2   state_3  state_6  state_8
state_1  state_11  state_13  state_16  state_18  state_20  state_5  state_7
```

Files:
```
config.json  model_1.safetensors  model.safetensors  optimizer.bin  random_states_0.pkl  scheduler.bin
```

**Comment by Liyuhui-12** [comment]
The specific filename depends on the code you used to save the weights. Based on your screenshot, it seems that the EAGLE weights were saved as model.safetensors. You could try loading the weights from model.safetensors.

**Comment by tjtanaa** [comment]
Thank you very much. Loading from safetensors work. However, I need to modify the scripts.
