### ISSUE TITLE
runtime

### ISSUE THREAD

**Issue by qspang** [SafeAILab/EAGLE#23]
![IRM%7{I%K_1A~NX~FQY{AUR](https://github.com/SafeAILab/EAGLE/assets/93046554/94ad5a04-6bee-440d-9d82-05eb606b893c)
how to solve this problem?I completely cloned the project and then transferred it to it, and then directly followed this evaluation without changing the code. Then the models were downloaded from hf. If I say changes, they are targeted changes to the runtime errors (after all, they are also changed. to run successfully (if I don’t change it, an error will still be reported),

**Comment by peoplekillerS** [comment]
![034e30a26e1cd87e3412b61b2761e8c](https://github.com/SafeAILab/EAGLE/assets/93046554/b90a4d3e-3c41-4bf8-95f6-c806a7b079fd)The above is my running command.Among them, llama2-7b-chat is downloaded from the meta official license, and the weight model is downloaded from the link of the project yuhuili/EAGLE-llama2-chat-7B, and according to the project requirements:pip install -r requirements.The graphics card I use is NVIDIA 3090.But I did not go through the training step in the project, but wanted to directly test the acceleration effect through the weights you gave.

**Comment by peoplekillerS** [comment]
When I used llama2-7b-chat-hf instead of llama2-7b-chat, I was surprised to find that it could run successfully, but vicuna-7b-v1.3 still failed. I guess the vicuna-7b-v1.3 format is not compatible with the huggingface format. Because we use transformers lib, a model weight compatible with transformers lib.I guess it is necessary to convert vicuna-7b-chat into a hugging face form like llama2-7b-chat-hf.

**Comment by Liyuhui-12** [comment]
Sure, in order to use Huggingface.transformers, you must use the -hf weights.

**Comment by peoplekillerS** [comment]
But the vicuna-7b-chat I used was downloaded from hugging-face! ! ! Link: https://huggingface.co/lmsys/vicuna-7b-v1.3

**Comment by Liyuhui-12** [comment]
Are you still encountering the same error? Can you generate normally using Huggingface's generate function?

**Comment by qspang** [comment]
> When I used llama2-7b-chat-hf instead of llama2-7b-chat, I was surprised to find that it could run successfully, but vicuna-7b-v1.3 still failed. I guess the vicuna-7b-v1.3 format is not compatible with the huggingface format. Because we use transformers lib, a model weight compatible with transformers lib.I guess it is necessary to convert vicuna-7b-chat into a hugging face form like llama2-7b-chat-hf.

I still can't run your EAGLE project normally using vicuna-7b-chat. I haven't tried using Huggingface's generate function yet.

**Comment by qspang** [comment]
Can you now use vicuna-7b-chat to run your EAGLE project normally?

**Comment by Liyuhui-12** [comment]
I can run it normally.
