### ISSUE TITLE
failed to reproduce given speedup results

### ISSUE THREAD

**Issue by ZepinLi** [SafeAILab/EAGLE#25]
hi EAGLE team,

thank you for great work!
we failed to acquire your speedup results with mi250(rocm). experimental outcomes of llama2-13b-chat and llama2-13b-chat are below,
<img width="581" alt="Screenshot 2024-01-09 at 17 33 20" src="https://github.com/SafeAILab/EAGLE/assets/70683930/de9ba22e-4982-4e33-b83c-92081a87caad">
 are your results really dependent on hardware? or, are we lost something crucial?

best.

**Comment by hongyanz** [comment]
There have been people who can reproduce our claimed numbers. Without more details about your setup, we suspect perhaps you are running something else in the backend? That will significantly affect the speed.

https://github.com/SafeAILab/EAGLE/issues/5

**Comment by alcholiclg** [comment]
Can I ask you how you solved the problem of not being able to reproduce the speedup ratio? I recently encountered a similar problem.

**Comment by nanxue2023** [comment]
> Can I ask you how you solved the problem of not being able to reproduce the speedup ratio? I recently encountered a similar problem.

same. Have you fixed it? @alcholiclg
