### ISSUE TITLE
Question about manual datasets & Some interests about details

### ISSUE THREAD

**Issue by HackGiter** [SafeAILab/EAGLE#30]
Thanks for your great job. I just have some curiosities about it.

First, would it be too big to store the hidden states directly as .ckpt file?  How large it is.
Second, could you provide ablation experiment about the cnet and decoding methods?

**Comment by Liyuhui-12** [comment]
It depends on the amount of data used and the hidden_size of the target LLM. Using ShareGPT (about 68k conversations), a model with hidden_size=4096 requires 740GB of disk space. The ablation experiment can be found in our [paper](https://arxiv.org/abs/2401.15077).

**Comment by Siegfried-qgf** [comment]
Is there other method to save hidden states？The space cost seems large.
