### ISSUE TITLE
Is there scripts to calculate the acceptance rate at each position?

### ISSUE THREAD

**Issue by agentup** [SafeAILab/EAGLE#39]

**Comment by Liyuhui-12** [comment]
The script for calculating the acceptance rate at each position is ./evaluation/gen_ea_alpha_llama2chat.py.

**Comment by xwjim** [comment]
> The script for calculating the acceptance rate at each position is ./evaluation/gen_ea_alpha_llama2chat.py.

Thanks for your reply.
