### ISSUE TITLE
Can EAGLE be applied to any auto-regressive model?

### ISSUE THREAD

**Issue by sam-sepiola** [SafeAILab/EAGLE#41]
How can I use EAGLE with a custom auto-regressive model that's not supported ( yet!) by default?

**Comment by Liyuhui-12** [comment]
Yes, EAGLE doesn't depend on the internal structure of LLM. When training EAGLE with a custom auto-regressive mode, it is important to adjust the instruction template accordingly.

**Comment by thyywr759** [comment]
In the ea_model.py:from_pretrained(), you used KVLlamaForCausalLM and KVMixtralForCausalLM as the base_model classes. 

If we were to use another model, such as qwen, as the base model, how would we change this part of the code

**Comment by Liyuhui-12** [comment]
@thyywr759 We have updated the Readme, and you can find the guide [here](https://github.com/SafeAILab/EAGLE/blob/main/README.md#inference-on-custom-models).
