### ISSUE TITLE
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by cyLi-Tiger** [SafeAILab/EAGLE#45]
Great work!

I tried your [example](https://github.com/SafeAILab/EAGLE#:~:text=llama%2D2%2Dchat%5D-,With%20Code,-You%20can%20use) for llama-7b-chat and changed the tree structure in choices.py into `baseline = [[0], [0, 0], [0, 0, 0], [0, 0, 0, 0]]` to simulate speculative decoding without token tree, and got the error above. Any clues?

log attached:
![image](https://github.com/SafeAILab/EAGLE/assets/37681002/17c3d8a9-844e-4a93-9a8a-1c4515ca4f57)

**Comment by Liyuhui-12** [comment]
This seems to be an issue with the original LLaMA2-Chat encountering NaN. What was your input?

**Comment by cyLi-Tiger** [comment]
> This seems to be an issue with the original LLaMA2-Chat encountering NaN. What was your input?

Simply "Hello"

**Comment by Liyuhui-12** [comment]
I can run this code normally. Did you use the correct weights for LLaMA2-Chat? It should be meta-llama/Llama-2-7b-chat-hf instead of meta-llama/Llama-2-7b-chat.

**Comment by cyLi-Tiger** [comment]
I got the tree shape wrong, my bad. Thanks!

**Comment by reyna-abhyankar** [comment]
What was wrong with your original tree shape @cyLi-Tiger? I am facing a similar issue
