### ISSUE TITLE
Generation quality loss

### ISSUE THREAD

**Issue by cyLi-Tiger** [SafeAILab/EAGLE#50]
Hi, I noticed you mentioned in paper that 

> evaluating the quality of EAGLE’s generated results is both unnecessary and meaningless.

But based on my experiments on both llama2-chat-7b and Qwen-chat-7b, EAGLE's generation quality declined on c-eval and human-eval. The result is attached.

![image](https://github.com/SafeAILab/EAGLE/assets/37681002/f92e85b0-442e-427e-96ed-ce520ca05582)

Baseline is the output from hf `model.generate()` , eagle is the output from `ea_model.eagenerate()`.

Have you done similar experiments? Any clues?

**Comment by Liyuhui-12** [comment]
EAGLE is a speculative sampling method, theoretically ensuring that the distribution of the generated text remains unchanged. The proof can be found in the Appendix A of the [paper](https://arxiv.org/abs/2211.17192). What were your test settings, greedy or non-greedy? Did the evaluators know which response was generated by EAGLE? There was a bug in EAGLE in the non-greedy setting before, which could lead to this issue.

**Comment by cyLi-Tiger** [comment]
non-greedy, can you share what's the bug? In case I got the same problem.

**Comment by Liyuhui-12** [comment]
The [bug](https://github.com/SafeAILab/EAGLE/pull/47) has been fixed now.

**Comment by cyLi-Tiger** [comment]
Btw, do you mind sharing your sampling parameters like `top_p` for non-greedy setting? I think smaller `top_p` make the decoding strategy more like greedy decoding. Based on my experiments, the accuracy result from eval is kind of not acceptable when using normal `top_p` value like 0.8, and it goes higher with smaller `top_p`. So if I want to get an acceptable accuracy, I need to set `top_p` like 0.2, which is not very common.

**Comment by cyLi-Tiger** [comment]
Another question, what's the point of this [MODIFIED](https://github.com/SafeAILab/EAGLE/blob/98c2db6b3315f64329f6df3f7933835568cae99d/model/modeling_llama_kv.py#L898C17-L898C70), what's gonna happen is the mask type not set to float32? Is it gonna cause accuracy loss?

**Comment by Liyuhui-12** [comment]
> Another question for this [MODIFIED](https://github.com/SafeAILab/EAGLE/blob/98c2db6b3315f64329f6df3f7933835568cae99d/model/modeling_llama_kv.py#L898C17-L898C70), what's gonna happen is the mask type not set to float32? Is it gonna cause accuracy loss?

This is copied from Medusa, and forcing the use of high precision should not result in a loss of quality.

**Comment by Liyuhui-12** [comment]
We have fixed a bug related to sampling. After fixing this bug, we conducted a large number of repeated experiments for validation. We replaced the original LLM with a model that outputs distributions based on position_ids and performed approximately 400,000 experiments. As shown in the figure below, the distribution of the original LLM is highly consistent with the data sampled using the current version of the code. Therefore, we believe there is no loss of quality now. You can find the code and the obtained data for this test in the ./testbug directory.
![image](https://github.com/SafeAILab/EAGLE/assets/81251885/17dd8ec5-317b-4a4f-9837-55feb1baf0a2)

**Comment by thyywr759** [comment]
> Hi, I noticed you mentioned in paper that
> 
> > evaluating the quality of EAGLE’s generated results is both unnecessary and meaningless.
> 
> But based on my experiments on both llama2-chat-7b and Qwen-chat-7b, EAGLE's generation quality declined on c-eval and human-eval. The result is attached.
> 
> ![image](https://private-user-images.githubusercontent.com/37681002/310367173-f92e85b0-442e-427e-96ed-ce520ca05582.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTk1MzMsIm5iZiI6MTcxMDE1OTIzMywicGF0aCI6Ii8zNzY4MTAwMi8zMTAzNjcxNzMtZjkyZTg1YjAtNDQyZS00MjdlLTk2ZWQtY2U1MjBjYTA1NTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDEyMTM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjhjM2I1MTE5ZDYyNTAxOGJlZmY0ZjUxYWE2NjJkNTBiMmQzNjI0MTgyZTc4ODE0NDcxYTM4N2QwOGRkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRbvDlvlO_Fn-elpFp-5vl31OLfxQfVZORZwsEkisSg)
> 
> Baseline is the output from hf `model.generate()` , eagle is the output from `ea_model.eagenerate()`.
> 
> Have you done similar experiments? Any clues?

can u share the modification code for using Qwen model to train and inference, thanks a lot

**Comment by w32zhong** [comment]
In my case, I set the model to be greedy (default ea_generate arguments), EAGLE's human-eval accuracy for LLaMA-7B drops to 5.49 from baseline's 8.54.

Any idea or related bug fixes?

**Comment by Hannibal046** [comment]
It seems there are two different implementation. I understand the latter one is lossless as proved in the [Fast Inference from Transformers via Speculative Decoding](https://arxiv.org/pdf/2211.17192). Could you share more insights about the former one?
https://github.com/SafeAILab/EAGLE/blob/35c78f6cdc19a73e05cf5c330b4c358dad970c6a/eagle/model/utils.py#L387
https://github.com/SafeAILab/EAGLE/blob/35c78f6cdc19a73e05cf5c330b4c358dad970c6a/eagle/testbug/model/utils.py#L377

**Comment by Liyuhui-12** [comment]
Both are lossless. In speculative sampling, q does not necessarily need to be the distribution of the draft model; it can be any distribution, such as a one-hot version (L387) of the draft model's distribution.
