### ISSUE TITLE
can you share ShareGPT dataset used to train the models?

### ISSUE THREAD

**Issue by arunpatala** [SafeAILab/EAGLE#51]
Can you provide the dataset or link where i can find the dataset (version 4.3 ShareGPT) ?

Ans thanks for this great repo.

**Comment by arunpatala** [comment]
If anyone else needs the dataset I have found this one.

https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered

I had to remove zero length rows and zero loss_mask rows to make it work. 

This can be closed.

**Comment by Liyuhui-12** [comment]
We used this [dataset](https://huggingface.co/datasets/Aeala/ShareGPT_Vicuna_unfiltered/blob/main/ShareGPT_V4.3_unfiltered_cleaned_split.json).

**Comment by arunpatala** [comment]
thanks
