### ISSUE TITLE
run with vllm

### ISSUE THREAD

**Issue by Hevans123** [SafeAILab/EAGLE#56]
Thanks for this great repo. I would like to know how is the progress to support with VLLM.
Or could you point me what major changes that need to be done. That would be very helpful.

**Comment by Liyuhui-12** [comment]
The draft model of EAGLE is essentially a Decoder layer of LLaMA, so two models should be created using the backend of vLLM, and the base model should be modified to output hidden states. The hidden states and input_ids should be concatenated, and then input into the draft model after dimension reduction. The most important thing to note is to modify the block table of PagedAttention to truncate rejected tokens.
