### ISSUE TITLE
Llama 3 support?

### ISSUE THREAD

**Issue by joshmackwilliams** [SafeAILab/EAGLE#67]
Is Llama 3 (specifically the instruct models) supported by the code as-is (Llama 2 path), or are changes required (e.g., to support the new tokenizer)?

And, do you have any plans to release a pretrained Eagle for Llama 3? (e.g., like https://huggingface.co/yuhuili/EAGLE-llama2-chat-7B)

**Comment by Liyuhui-12** [comment]
You need to modify the instruction templates (such as those in eagle/ge_data/ge_data_all_vicuna.py). Training the draft model for LLaMA 3 is our next step.

**Comment by Liyuhui-12** [comment]
Hey @kalradivyanshu, support for LLaMA3 has now been updated.
