### ISSUE TITLE
Why does instruction_len need to subtract 2?

### ISSUE THREAD

**Issue by cdliang11** [SafeAILab/EAGLE#77]
https://github.com/SafeAILab/EAGLE/blob/667ba930db7ea0075421f3c7df94ffbc10b93805/eagle/ge_data/ge_data_all_llama2chat.py#L114-L115

For the llama3 model, does instruction_len also need to subtract 2?

**Comment by cdliang11** [comment]
done

**Comment by xiongqisong** [comment]
do you know why?@cdliang11
