### ISSUE TITLE
Question about alpha

### ISSUE THREAD

**Issue by zkqq** [SafeAILab/EAGLE#80]
Thank you very much for your work on EAGLE; it has been extremely helpful to me.

Could you please clarify what **alpha** means in this context? Does it refer to the accuracy of the EAGLE draft head in autoregressively predicting the next n tokens without using tree attention?

I look forward to your response. Thank you.

**Comment by Liyuhui-12** [comment]
> Does it refer to the accuracy of the EAGLE draft head in autoregressively predicting the next n tokens without using tree attention?

Yes. The input of the draft model is a feature sequence, part of which comes from the base model without errors, and part of which comes from the predictions of the draft model with errors. The acceptance rate of inputting n erroneous features is n-alpha.

**Comment by zkqq** [comment]
> > Does it refer to the accuracy of the EAGLE draft head in autoregressively predicting the next n tokens without using tree attention?
> 
> Yes. The input of the draft model is a feature sequence, part of which comes from the base model without errors, and part of which comes from the predictions of the draft model with errors. The acceptance rate of inputting n erroneous features is n-alpha.

Thank you very much for your response; it has been extremely helpful to me.

I have a follow-up question regarding the term **alpha_num**. Could you please explain its meaning? Additionally, why is it necessary to divide **alpha** by **alpha_num** when calculating the accuracy of the draft head, rather than dividing **alpha** by **the number of drafts**?

I look forward to your clarification. Thank you once again for your assistance.

**Comment by Liyuhui-12** [comment]
![image](https://github.com/SafeAILab/EAGLE/assets/81251885/2af55c3f-556e-4cb9-a1c5-cb9f08139b4f)
