### ISSUE TITLE
I use Chinese and English mixed dataset  and a another custom 7B model to train eagle，but the performance in Chinese is not good enough

### ISSUE THREAD

**Issue by 2024WY** [SafeAILab/EAGLE#81]
I had modified the preprocess_function.And the used data is the sft data of the model.
The pictures are the results of the training and testing in training:
![train](https://github.com/SafeAILab/EAGLE/assets/173039829/a218955c-3037-4bed-a7e7-60ad6d64bd77)
![test](https://github.com/SafeAILab/EAGLE/assets/173039829/3c58fbe0-c8a1-46e0-8705-bed0dd4e9bab)

but I use Spec-Bench project to test on Chineses dataset, the Mean accepted tokens is only 2.5994782086414654, not good enough.

Anything else to pay attention, Can you give some advice?Thanks!

**Comment by Liyuhui-12** [comment]
I noticed that your top-3 accuracy on the training set is only about 0.8, which is relatively low. What is your training accuracy on the English dataset? If it is close to the accuracy on the Chinese dataset, it could be that the structure or size of the draft model is not suitable. If the English accuracy is significantly higher than the Chinese accuracy, it is possible that your base model is not sufficiently trained on Chinese, and its features cannot effectively capture the semantic information of Chinese.
