### ISSUE TITLE
number of draft token

### ISSUE THREAD

**Issue by Monoclinic** [SafeAILab/EAGLE#87]
Hello, I found that the best number of draft token is determined empirically:
https://github.com/SafeAILab/EAGLE/blob/35854779f60db028ec646d945cacbdebdce490bb/eagle/model/ea_model.py#L127

I'm little confused about the meaning of x here. How to get the value of x and why the time should be divided by x?

**Comment by Liyuhui-12** [comment]
This is a rough estimate for quickly running the demo. The more draft tokens, the longer the acceptance length, so dividing by a number greater than 1 is used to balance it.

**Comment by Monoclinic** [comment]
I see. Thank you.
