### ISSUE TITLE
alpha value differs from what is reported in the paper

### ISSUE THREAD

**Issue by fousdfrf** [SafeAILab/EAGLE#89]
![image](https://github.com/SafeAILab/EAGLE/assets/77431106/da84e4f3-13a2-4de2-a9b7-2c6466a8e0a1)

I encountered an issue while testing eagle-1 and llama-2-7b on the 4090 using the mt_beach dataset. The speed ratio is normal, but the alpha values do not match those reported in the research paper.

python -m eagle.evaluation.gen_ea_alpha_llama2chat --ea-model-path /models/EAGLE-llama2-chat-7B --base-model-path models/modelscope/Llama-2-7b-chat-ms --model-id ea-alpha-llama-2-chat-7b-fp16   --temperature 0.0 

python mt_bench/alpha.py

**Comment by HofieR** [comment]
I meet the same situation.

**Comment by Liyuhui-12** [comment]
You might have used tree attention.
