### ISSUE TITLE
can eagle support

### ISSUE THREAD

**Issue by zhangxy1234** [SafeAILab/EAGLE#90]
when I inference multi batch, it raise an Error 

RuntimeError: output with shape [1, 32, 84, 128] doesn't match the broadcast shape [2, 32, 84, 128]

**Comment by haiduo** [comment]
Is it because of the dynamic tree attention mechanism that Eagle2 does not support batch size>1?

**Comment by Liyuhui-12** [comment]
EAGLE-2 requires some code modifications to support bs>1, so it temporarily does not support bs>1.

**Comment by zhangxy1234** [comment]
> Only EAGLE-1 supports bs > 1 now.

how can EAGLE-1 supports bs = 2? 

the model is :
model = EaModel.from_pretrained(
    base_model_path=base_model_path,
    ea_model_path=EAGLE_model_path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    device_map="auto",
    pretraining_tp = 1,
)

and the input is : input_ids=model.tokenizer([prompt1,prompt2]).input_ids
but it raise an error 
RuntimeError: output with shape [1, 32, 44, 128] doesn't match the broadcast shape [2, 32, 44, 128]
@hongyanz

**Comment by zhangxy1234** [comment]
> Only EAGLE-1 supports bs > 1 now.

can you show me an example to use bs = 2 ?

I create model and prompts  this way but it raise this error
model = EaModel.from_pretrained(
    base_model_path=base_model_path,
    ea_model_path=EAGLE_model_path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    device_map="auto",
    pretraining_tp = 1, # use if tp>1 
)


input_ids=model.tokenizer([prompt1,prompt2]).input_ids


RuntimeError: output with shape [1, 32, 44, 128] doesn't match the broadcast shape [2, 32, 44, 128]



@hongyanz

**Comment by hongyanz** [comment]
You can go to the v1 branch and check here: https://github.com/SafeAILab/EAGLE/tree/v1?tab=readme-ov-file#batch-size--1

**Comment by DeclK** [comment]
> EAGLE-2 requires some code modifications to support bs>1, so it temporarily does not support bs>1.

Can you give some hints about how to make EAGLE2 for batch inference? If the tree mask is not the same for different batch, how can we modify this?
