### ISSUE TITLE
Why qx = 1.0 in Eagle2? 

### ISSUE THREAD

**Issue by haiduo** [SafeAILab/EAGLE#93]
https://github.com/SafeAILab/EAGLE/blob/35854779f60db028ec646d945cacbdebdce490bb/eagle/model/utils.py#L387

**Comment by Liyuhui-12** [comment]
Because top-k sampling is used in the draft phase, when a previous draft token is rejected, the sampling probability of the current draft token is 1.

**Comment by haiduo** [comment]
Hi @Liyuhui-12 , Haha, I finally got it, thank you for your reply!
