### ISSUE TITLE
training sometimes crashes down

### ISSUE THREAD

**Issue by Monoclinic** [SafeAILab/EAGLE#94]
Hello, I tried to train eagle on 4x A6000 and found that the training process could crash down sometimes. The error seems to be about multi-gpu connection timeout (>30min).
I suspected it's because of crashing of one gpu, however all gpus works properly until the whole program is down (according to the temperature), it's strange to throw a timeout.
![image](https://github.com/user-attachments/assets/3783b6a3-f273-4e53-bd88-5b336b3dbba1)
Although I think it's my own problem, I would appreciate it if you have any experience or advice to address this problem. Thank you!

**Comment by Liyuhui-12** [comment]
Are there any error messages?
