### ISSUE TITLE
error 'accept_length' in Eagle1 or 2?

### ISSUE THREAD

**Issue by haiduo** [SafeAILab/EAGLE#95]
https://github.com/SafeAILab/EAGLE/blob/35854779f60db028ec646d945cacbdebdce490bb/eagle/evaluation/gen_ea_alpha_vicuna.py#L93

It looks like a bug? The calculation of accept_length only considers the last step of the last conversation, not the average result. The results I reproduced are basically accept_length=2.
Experimental settings: LLM=vicuna-7b, test: MT-bench

**Comment by haiduo** [comment]
> They didn't release the average accept length script, you can simply dump them into jsonl file and calculate them yourself.

Yes, I used the modified script to calculate the average length, but the result was 2.0.

**Comment by yanjunplay** [comment]
Hi @haiduo, curious, did you have any update on this? :-)

**Comment by haiduo** [comment]
> Hi @haiduo, curious, did you have any update on this? :-)

Hello. I try other devices(different GPUs) and the conclusions are basically the same as mine. I also look at the implementations of other open source [frameworks](https://github.com/hemingkx/Spec-Bench/blob/6069baeed5019bd88b924057fef22a67b9463e60/evaluation/inference_eagle.py#L100) and they are the same as mine. So I have reason to believe that the author either doesn't open source the complete actual test codes or his paper results are problematic.
In addition, the baseline and eagle results in the table above are reversed, and the unit is token/s.

**Comment by yanjunplay** [comment]
Thanks @haiduo for replying me. I just checked the Spec Bench dashboard https://github.com/hemingkx/Spec-Bench/blob/main/Leaderboard.md from the link you shared. Their "Accepted Tokens" numbers for EAGLE are all 3+. You mean the logic there was correct? Then I am a bit confused how do they get 3+ while we can only get ~2 here for EAGLE 2? Have you tried the Spec-Bench scripts?

**Comment by haiduo** [comment]
Thank you for your comment @yanjunplay . I don't reproduce the results of Spec Bench in time (but I am going to do so), I just look at the experiment of that code. In addition, the above results are problematic when using the code of eagle2 to test the accept length directly. I use the code of eagle1 (according to the author's previous reply in the issue). If there is a problem with my reproduction, it may be that I don't use chain speculation (used by the paper), but only use eagle1's "gen_ea_alpha_vicuna.py". In fact, its test is a tree with 26 nodes, that is, tree speculation. But even so, why can the values ​​of accept rate (0-alpha, 1-alpha, 2-alpha) be correct? I am confused.
Finally, I need to ask you about the [question](https://github.com/SafeAILab/EAGLE/issues/93) I raised before. The author implements it differently in eagle2 and eagle1. I don't know if q(x)=1 still meets the same distribution assumption of speculative sampling.

**Comment by yanjunplay** [comment]
@haiduo do you use wechat? Maybe we can quickly discuss a bit. Mine wechat account: macazi

**Comment by haiduo** [comment]
> @haiduo do you use wechat? Maybe we can quickly discuss a bit. Mine wechat account: macazi

That's good!

**Comment by qwedaq** [comment]
> Thank you for your comment @yanjunplay . I don't reproduce the results of Spec Bench in time (but I am going to do so), I just look at the experiment of that code. In addition, the above results are problematic when using the code of eagle2 to test the accept length directly. I use the code of eagle1 (according to the author's previous reply in the issue). If there is a problem with my reproduction, it may be that I don't use chain speculation (used by the paper), but only use eagle1's "gen_ea_alpha_vicuna.py". In fact, its test is a tree with 26 nodes, that is, tree speculation. But even so, why can the values ​​of accept rate (0-alpha, 1-alpha, 2-alpha) be correct? I am confused. BTW, the author's open-source eagle2 can only train and test the speedup results currently, so the results I reproduced are based on eagle1 without any changes. Finally, I need to ask you about the [question](https://github.com/SafeAILab/EAGLE/issues/93) I raised before. The author implements it differently in eagle2 and eagle1. I don't know if q(x)=1 still meets the same distribution assumption of speculative sampling.

Hi @haiduo, were you able to get any answer as to why qx=1.0 in EAGLE2?

**Comment by haiduo** [comment]
Hi @qwedaq, although we don't receive a reply from the author, we deduce it later and find that in the non-repeat sampling mode of Eagle2, q(x)=1.0 is a special case of speculative decoding, which only applies to Eagle2. It is not reasonable for Eagle1. Therefore, Eagle2 should have no problem doing this in theory, but I haven't had time to try it out to see how the actual generated quality is. You can try to use other benchmarks to measure its score.

**Comment by qwedaq** [comment]
> Hi @qwedaq, although we don't receive a reply from the author, we deduce it later and find that in the non-repeat sampling mode of Eagle2, q(x)=1.0 is a special case of speculative decoding, which only applies to Eagle2. It is not reasonable for Eagle1. Therefore, Eagle2 should have no problem doing this in theory, but I haven't had time to try it out to see how the actual generated quality is. You can try to use other benchmarks to measure its score.

Thank you for your quick response. I am a bit new to speculative decoding can you please elaborate on what you mean by non-repeat sampling model of EAGLE2?

**Comment by haiduo** [comment]
> > Hi @qwedaq, although we don't receive a reply from the author, we deduce it later and find that in the non-repeat sampling mode of Eagle2, q(x)=1.0 is a special case of speculative decoding, which only applies to Eagle2. It is not reasonable for Eagle1. Therefore, Eagle2 should have no problem doing this in theory, but I haven't had time to try it out to see how the actual generated quality is. You can try to use other benchmarks to measure its score.
> 
> Thank you for your quick response. I am a bit new to speculative decoding can you please elaborate on what you mean by non-repeat sampling model of EAGLE2?

Firstly, you may need to read the two papers: "Fast Inference from Transformers via Speculative Decoding" and "Accelerating Large Language Model Decoding with Speculative Sampling".  Secondly, my understanding of "sampling without replacement" or "non-repeat" is similar to what we describe in probability statistics: each time a sample is drawn, whether accepted or not, it is excluded from the total sample pool before the next round of sampling. Hope to help you.

**Comment by qwedaq** [comment]
Got it. Will read the papers you mentioned. Thank you again :)

**Comment by 870572761** [comment]
> Thank you for your comment [@yanjunplay](https://github.com/yanjunplay) . I don't reproduce the results of Spec Bench in time (but I am going to do so), I just look at the experiment of that code. In addition, the above results are problematic when using the code of eagle2 to test the accept length directly. I use the code of eagle1 (according to the author's previous reply in the issue). If there is a problem with my reproduction, it may be that I don't use chain speculation (used by the paper), but only use eagle1's "gen_ea_alpha_vicuna.py". In fact, its test is a tree with 26 nodes, that is, tree speculation. But even so, why can the values ​​of accept rate (0-alpha, 1-alpha, 2-alpha) be correct? I am confused. BTW, the author's open-source eagle2 can only train and test the speedup results currently, so the results I reproduced are based on eagle1 without any changes. Finally, I need to ask you about the [question](https://github.com/SafeAILab/EAGLE/issues/93) I raised before. The author implements it differently in eagle2 and eagle1. I don't know if q(x)=1 still meets the same distribution assumption of speculative sampling.

Hi. I have the same doubts as you about this method.
I even think that this method is unreasonable. This approach negates the assumption of lossless inference in "Accelerating Large Language Model Decoding with Speculative Sampling". I'm not sure if you have fixed this bug yet. After I fixed it, I achieved good results in other types of tasks. I wonder if it's possible to share and discuss with you the outcome of my code correction efforts.
