### ISSUE TITLE
Training config for llama3 

### ISSUE THREAD

**Issue by yanjunplay** [SafeAILab/EAGLE#97]
Hello, can you help to add training config for llama 3 models (8B and 70B)? 
Currently, I only see training configs for llama 2 in folder https://github.com/SafeAILab/EAGLE/tree/main/eagle/train

Thanks a lot!

**Comment by yanjunplay** [comment]
Actually, I found it on hf https://huggingface.co/yuhuili/EAGLE-LLaMA3-Instruct-70B/blob/main/config.json
I think we just need to copy them to this git repo.

**Comment by Liyuhui-12** [comment]
I have already copied it over.
