### ISSUE TITLE
Best performance for fine tuned llama3 70b model

### ISSUE THREAD

**Issue by yanjunplay** [SafeAILab/EAGLE#98]
Hello, thanks again for the awesome work!

I am trying EAGLE-2 on a fine tuned llama3 70b model. I did some benchmark and found that the acceleration ratio for my fine tuned llama3 model is much lower then the open sourced llama3 70B.

Comparison setup:
1. Open sourced llama3 70B https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct + https://huggingface.co/yuhuili/EAGLE-LLaMA3-Instruct-70B
2. My fine tuned llama3 70B + https://huggingface.co/yuhuili/EAGLE-LLaMA3-Instruct-70B

The acceleration ratio of #2 is much lower than #1. (Both were tested with the benchmark [script](https://github.com/SafeAILab/EAGLE/blob/main/eagle/evaluation/gen_ea_answer_llama3chat.py) )

I assume I should re-train the EAGLE model (head) with my fine tuned llama3 70B model as base model?

**Comment by Liyuhui-12** [comment]
Yes, the draft model needs to correspond with the base model, so you will need to retrain the draft model.

**Comment by yanjunplay** [comment]
Correct! I trained and saw the perf became better!
